### ISSUE TITLE
Add 'SENTRY_WIZARD_PROJECT' Option

### ISSUE THREAD

**Issue by AlexAtkinson-Myant** [getsentry/sentry-wizard#111]
Please add an argument for passing in the Project when the Quiet is being used in a cicd pipe.
Additionally, it's not clear how Quiet would work otherwise.

Thanks,
A

**Comment by lobsterkatie** [comment]
Hi, @AlexAtkinson-Myant.

Can you please help me understand your use case better? When would you be setting up a new project in CI?
