### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] (Node 14)

### ISSUE THREAD

**Issue by AlexAtkinson-Myant** [getsentry/sentry-wizard#112]
### Environment

USE: SAAS
SDK: "@sentry/react-native": "^2.2.1",
node: v14.17.0
react-native-cli: 2.0.1
react-native: 0.61.5

### Steps to Reproduce

1. run: `react-native link @sentry/react-native`

### Expected Result

The linkening.

### Actual Result

```
✅ Patched build.gradle file.
✅ Patched App.js file.
✅ Added sentry.properties file to android
Successfully set up android for react-native
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1517:5)
    at /.../git/.../node_modules/@sentry/wizard/dist/lib/Helper/File.js:33:20
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

🎉  Successfully set up Sentry for your project 🎉
done
```

### NOTE

This worked (not great, as the releases never reflected the events in the web portal), in 12.x., but it seems like 14 has dialed up the strictness.

**Comment by sykaeh** [comment]
I'm having the same issue, but running sentry-wizard directly:

```
$ npx sentry-wizard

Running Sentry Wizard...
version: 1.2.0 | sentry-cli version: 1.64.2
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)
Please open
https://sentry.io/account/settings/wizard/{redacted}/
in your browser (if it's not open already)

Sentry Wizard failed with:
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1460:5)
    at /Users/ehrensbe/repositories/wir.viac.frontend/app/node_modules/@sentry/wizard/dist/lib/Helper/File.js:33:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Protip: Add --debug to see whats going on
OR use --help to see your options
```

It just hangs and does not complete. I am also using Node v14 (14.16.0).

This seems to be a **regression** introduced in sentry-wizard 1.2.0. Everything works fine with v1.1.4.

**Comment by arnaudambro** [comment]
> Edit: This seems to be only happening some of the time. I can run the exact same command twice and once it works and once it does not.

Same story for me !

Do you have a fix for that ?
