### ISSUE TITLE
Missing react/javascript integration options

### ISSUE THREAD

**Issue by SevenOutman** [getsentry/sentry-wizard#120]
### Steps to Reproduce

    npx @sentry/wizard

### Expected Result

I'm trying to use sentry-wizard to setup sentry integration in my react webpack project. The *What integration do you want to setup* prompt should come with a `React` or at least `JavaScript` option.

### Actual Result

No such options.

![image](https://user-images.githubusercontent.com/8225666/124716004-2c561880-df36-11eb-8387-a40b36d5cb1e.png)

**Comment by AbhiPrasad** [comment]
This is difficult for us to support due to the wide variety of possible webpack setups a user might have. Even more complex when there are multiple bundlers: esbuild, parcel, snowpack, rollup used by the JavaScript community.

Is there something that was missing from https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/ that would have been helpful to have?

**Comment by SevenOutman** [comment]
> This is difficult for us to support due to the wide variety of possible webpack setups a user might have.

That makes sense. But the [options explanation](https://github.com/getsentry/sentry-wizard#options) says `javascript` is an available integration, which makes me confused. Maybe it should be deleted from the docs?

> Is there something that was missing from https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/ that would have been helpful to have?

Yes, this react integration guide was good enough to help me setup my project with `@sentry/webpack-plugin`. I was just wondering whether this wizard is designed to be the recommended way for setting up javascript/react/webpack projects.

**Comment by AbhiPrasad** [comment]
Thanks for the feedback and quick response! I opened https://github.com/getsentry/sentry-wizard/pull/124 to update the README - you're right that `javascript` shouldn't be an available option. 

We'll also take some more steps to make it more clear that the wizard is meant to be used with more advanced config setups like mobile, desktop and next. I'm thinking though we could probably link to the docs for other platforms, like `node` or `js` (so even if you run `npx @sentry/wizard`, you'll be directed to the right place).

**Comment by SevenOutman** [comment]
Thanks for your explanation!
