### ISSUE TITLE
Does not detect next version "^10.2" as valid

### ISSUE THREAD

**Issue by Naddiseo** [getsentry/sentry-wizard#121]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
"@sentry/nextjs": "^6.8.0",
### Steps to Reproduce

I have my next version as `"next": "^10.2"` (or "^10.2.x" in another project)

$ ./node_modules/.bin/sentry-wizard -i nextjs
Running Sentry Wizard...
version: 1.2.10 | sentry-cli version: 1.67.1
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)

✗ Your installed version of `next` is not supported, >10.0.0 needed

### Expected Result
It should detect that "^10.2" is > "10.0.0"

### Actual Result
Complains the next version is not supported

**Comment by AbhiPrasad** [comment]
Will be fixed by https://github.com/getsentry/sentry-wizard/pull/122
