### ISSUE TITLE
Stuck on "Waiting for wizard to connect"

### ISSUE THREAD

**Issue by dancherb** [getsentry/sentry-wizard#125]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
React Native 0.64.0
Windows 10

### Steps to Reproduce
1. npx @sentry/wizard -i reactNative -p ios android
2. �  Successfully set up Sentry for your project �
3. Waiting for wizard to connect (forever)

**Comment by xgenem** [comment]
Sentry is widely used, how come this has no responses?

**Comment by Lms24** [comment]
Hi, sorry for not responding here, this is on us. 
We changed quite a bit in the wizard and might have fixed this problem along the way.
Given that this issue seems to be discussed in #31 I'm gonna close this one for the time being. Please let me know if this issue should be reopened.
