### ISSUE TITLE
Error: Cannot find module '/root/.npm/_npx/43/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/scripts/install.js'

### ISSUE THREAD

**Issue by github0013** [getsentry/sentry-wizard#130]
### Environment

```
# cat Dockerfile | grep FROM
FROM node:lts-alpine

# uname -a
Linux 0e67118bc785 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 Linux

# node -v
v14.17.0

# cat package.json | grep next
    "@sentry/nextjs": "^6.12.0",
    "next": "^11.0.1",

```

### Steps to Reproduce

1. https://sentry.io/onboarding/ajoasi/get-started/
2. yarn add @sentry/nextjs
3. npx @sentry/wizard -i nextjs

### Expected Result

> Sentry wizard will automatically patch your application:

### Actual Result

Error: Cannot find module '/root/.npm/_npx/43/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/scripts/install.js'

I ran the `yarn add @sentry/nextjs` under `/app` and it was installed in `/app/node_modules` but the error shows something is trying to pull a script from `/root`

**Comment by AbhiPrasad** [comment]
Hey, thanks for writing in. Can you run the wizard in debug mode with `npx @sentry/wizard --debug -i nextjs` and post the output?

**Comment by github0013** [comment]
```
/app # npx @sentry/wizard --debug -i nextjs
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/7/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/scripts/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.68.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.68.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-14T02_36_04_027Z-debug.log
Install for [ '@sentry/wizard@latest' ] failed with code 1
```

**Comment by AbhiPrasad** [comment]
This might be an issue with stale caches. Please try running `npm cache verify` to see if there are any issues. 

You can also remove just the wizard: `rm -rf ~/.npm/_npx/7/lib/node_modules/@sentry/wizard`.

Do these help?

**Comment by github0013** [comment]
```
/app # npm cache verify
Cache verified and compressed (~/.npm/_cacache):
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.013s
```

```
/app # tree ~/.npm/
/root/.npm/
└── _cacache
    └── _lastverified
```

```
/app # npx @sentry/wizard -i nextjs
...
... the error messages..., then

/app # ls -al ~/.npm/_npx/7/lib/node_modules/@sentry
ls: /root/.npm/_npx/7/lib/node_modules/@sentry: No such file or directory

/app # tree -L 2 ~/.npm/
/root/.npm/
├── _cacache
│   ├── _lastverified
│   ├── content-v2
│   ├── index-v5
│   └── tmp
├── _locks
├── _logs
│   └── 2021-09-17T01_13_40_513Z-debug.log
├── _npx
└── anonymous-cli-metrics.json
```

I don't know if you've noticed, but I am running this in a docker container (node:lts-alpine).  Can this be a reason?

**Comment by meska** [comment]
This issue [#888](https://github.com/getsentry/sentry-cli/issues/888) on sentry-cli seems to have a solution

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
