### ISSUE TITLE
Use internal integrations instead of personal auth token

### ISSUE THREAD

**Issue by opiation** [getsentry/sentry-wizard#136]
When using the wizard to configure the Sentry client, it creates a auth token under the Sentry user's account to presumably access Sentry.

If one looks at the auth token in the Sentry web UI, one is immediately faced with this warning:

> Auth Tokens are tied to the logged in user, meaning they'll stop working if the user leaves the organization! We suggest using internal integrations to create/manage tokens tied to the organization instead.

Unfortunately, neither the [wizard documentation][0] nor the [manual config documentation][1] explain what the auth token is for or why it is used instead of an internal integration.

> [...] create `.sentryclirc` with the auth token for `sentry-cli` (which is automatically added to the `.gitignore`)

> The SentryWebpackPlugin uses sentry-cli to manage releases and source maps, [...]

> [...] and the auth token authenticates your user account.

This seems to suggest that my personal auth token will be needed to upload source maps. Does this mean that disabling my user account in Sentry or leaving the organization will effectively disable uploading source maps and releases? If so, how can an internal integration (at the organization level) be used instead, as recommended by the warning on the auth token page? Can this be option be added to the docs and would that make a better default for the wizard?

[0]: https://docs.sentry.io/platforms/javascript/guides/nextjs/#configure
[1]: https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#configure-sentry-cli

**Comment by opiation** [comment]
I would like to set up some source map upload automation that authenticates against an API key, group token, etc. instead of a personal authentication token. I sometimes perform contractual or transient work for companies setting up their projects and automation. In those cases, I'm not really a member of their organization and my involvement with them is temporary. Setting up my user as a member of their org and then revoking my access privileges when I'm done setting them up would effectively break their automation. Keeping me as a member would grant me access that I shouldn't have after my DevOps work for them is done.

I've used many other automation tooling that uses API keys, group access tokens, service accounts, etc. to authenticate various automation tasks so that changes to the dev team don't require checking every project's config files for tokens that _might_ be attached to an individual that is leaving the company. This is especially true for tooling that does not get frequent attention like this sort of automation. This seems like a prime use case for team or org-based tokens so that disabling a user account doesn't take down an entire company's build pipelines.

**Comment by iker-barriocanal** [comment]
I see, is https://docs.sentry.io/product/integrations/integration-platform/#auth-tokens-1 what you are looking for?
