### ISSUE TITLE
Sentry wizard fails to connect when executed from WSL

### ISSUE THREAD

**Issue by CameronDiver** [getsentry/sentry-wizard#138]
### Environment

It appears that the wizard simply dies after trying to open the browser when being executed from within WSL. I switched over to powershell in the same WSL directory and everything worked fine. 

Windows 10
WSL 2

How do you use Sentry?
Sentry SaaS

Which SDK and version?
Sentry wizard: v1.2.13

### Steps to Reproduce

Open a WSL terminal, navigate to a code directory and execute sentry-wizard. It will die on "Waiting for Sentry..."

### Expected Result

It opens the browser for me, and waits for the incoming sentry connection.

### Actual Result

The wizard dies, likely from trying to open the browser from within WSL. Logs here:
```
myproject $ sentry-wizard -i nextjs --debug
{
        "_": [],
        "i": "nextjs",
        "integration": "nextjs",
        "debug": true,
        "uninstall": false,
        "skip-connect": false,
        "skipConnect": false,
        "quiet": false,
        "u": "https://sentry.io/",
        "url": "https://sentry.io/",
        "$0": "sentry-wizard"
}
Running Sentry Wizard...
version: 1.2.13 | sentry-cli version: 1.69.1
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)

✓ next >= 10.0.8 is installed

/
Loading wizard for https://sentry.io/



Please open
https://sentry.io/account/settings/wizard/XXX/
in your browser (if it's not open already)


{
        "integration": {
                "_argv": {
                        "_": [],
                        "i": "nextjs",
                        "integration": "nextjs",
                        "debug": true,
                        "uninstall": false,
                        "skip-connect": false,
                        "skipConnect": false,
                        "quiet": false,
                        "u": "https://sentry.io/",
                        "url": "https://sentry.io/",
                        "$0": "sentry-wizard"
                },
                "_isDebug": true,
                "_sentryCli": {
                        "_argv": {
                                "_": [],
                                "i": "nextjs",
                                "integration": "nextjs",
                                "debug": true,
                                "uninstall": false,
                                "skip-connect": false,
                                "skipConnect": false,
                                "quiet": false,
                                "u": "https://sentry.io/",
                                "url": "https://sentry.io/",
                                "$0": "sentry-wizard"
                        }
                },
                "_shouldConfigure": {}
        },
        "hash": "XXX"
}

/
Polling: https://sentry.io/api/0/wizard/XXX/

/ Waiting for Sentry...
[Process exited]
```

Note that I'm not blocked by this as I figured it out, but the UX was quite confusing, so might be worth trying to detect WSL or at the minimum not dying if a browser window can't be opened.

**Comment by iker-barriocanal** [comment]
What happens if you manually open the link in the browser?

**Comment by bcetienne** [comment]
Same problem here.

Windows 11 22H2 (build 22621.1105)
WSL2 kernel 5.10.102.1

```
$ npx @sentry/wizard -i nextjs
Running Sentry Wizard...
version: 2.4.2 | sentry-cli version: 1.74.6
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)

✓ A compatible version of `next` is specified in `package.json`.
✓ A compatible version of `@sentry/nextjs` is specified in `package.json`.



Please open
https://sentry.io/account/settings/wizard/g0n5qa0g6eb9ykzwswn9awn7kroc1usjkxktw6o0jovczf0bup1bidhzzlo9m30v/
in your browser (if it's not open already)

\ Waiting for Sentry...<HERE IT CRASH INSTANTLY>
```

I do not have time to open URL...

**Comment by CardanoDur** [comment]
Can confirm, not a stale issue, still happening on wsl2

{
        "_": [],
        "i": "nextjs",
        "integration": "nextjs",
        "debug": true,
        "uninstall": false,
        "skip-connect": false,
        "skipConnect": false,
        "quiet": false,
        "u": "https://sentry.io/",
        "url": "https://sentry.io/",
        "s": false,
        "signup": false,
        "$0": "../../../.npm/_npx/a8388072043b4cbc/node_modules/.bin/sentry-wizard"
}
Running Sentry Wizard...
version: 2.6.1 | sentry-cli version: 1.75.0
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)

✓ A compatible version of `next` is specified in `package.json`.
✓ A compatible version of `@sentry/nextjs` is specified in `package.json`.

/
Loading wizard for https://sentry.io/



Please open
https://sentry.io/account/settings/wizard/it9ghkp2s5shgonjcbylxxlpf10rj39at1ggq6l1fnfeh2i9pyycu35709qt9vem/
in your browser (if it's not open already)


{
        "integration": {
                "_argv": {
                        "_": [],
                        "i": "nextjs",
                        "integration": "nextjs",
                        "debug": true,
                        "uninstall": false,
                        "skip-connect": false,
                        "skipConnect": false,
                        "quiet": false,
                        "u": "https://sentry.io/",
                        "url": "https://sentry.io/",
                        "s": false,
                        "signup": false,
                        "$0": "../../../.npm/_npx/a8388072043b4cbc/node_modules/.bin/sentry-wizard"
                },
                "_isDebug": true,
                "_sentryCli": {
                        "_argv": {
                                "_": [],
                                "i": "nextjs",
                                "integration": "nextjs",
                                "debug": true,
                                "uninstall": false,
                                "skip-connect": false,
                                "skipConnect": false,
                                "quiet": false,
                                "u": "https://sentry.io/",
                                "url": "https://sentry.io/",
                                "s": false,
                                "signup": false,
                                "$0": "../../../.npm/_npx/a8388072043b4cbc/node_modules/.bin/sentry-wizard"
                        }
                },
                "_shouldConfigure": {}
        },
        "hash": "it9ghkp2s5shgonjcbylxxlpf10rj39at1ggq6l1fnfeh2i9pyycu35709qt9vem"
}

/
Polling: https://sentry.io/api/0/wizard/it9ghkp2s5shgonjcbylxxlpf10rj39at1ggq6l1fnfeh2i9pyycu35709qt9vem/

/ Waiting for Sentry...
Polling received data


Polling received:


Error: Received status 400
    at WaitForSentry.<anonymous> (/home/couch/.npm/_npx/a8388072043b4cbc/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:95:63)
    at step (/home/couch/.npm/_npx/a8388072043b4cbc/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:46:23)
    at Object.next (/home/couch/.npm/_npx/a8388072043b4cbc/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:27:53)
    at fulfilled (/home/couch/.npm/_npx/a8388072043b4cbc/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:18:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
