### ISSUE TITLE
Sentry Wizard failed with: no projects

### ISSUE THREAD

**Issue by bonesoul** [getsentry/sentry-wizard#145]
[

- [x ] Review the documentation: https://docs.sentry.io/
- [x] Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-javascript/releases
- [x] Provide a link to the affected event from your Sentry account

### Version:

```
    "next": "11.1.2",
   "@sentry/nextjs": "6.14.0",
```

## Description

following the documentation here to install sentry on my next.js project

https://docs.sentry.io/platforms/javascript/guides/nextjs/

running 'npx @sentry/wizard -i nextjs' gives the error

```
Running Sentry Wizard...
version: 1.2.15 | sentry-cli version: 1.71.0
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)

✓ A compatible version of `next` is specified in `package.json`.



Please open

in your browser (if it's not open already)


Sentry Wizard failed with:
no projects

Protip: Add --debug to see whats going on
OR use --help to see your options

```

**Comment by AbhiPrasad** [comment]
Hey thanks for reporting. Could you provide the logs when you run the command with the `—debug` option?

**Comment by bonesoul** [comment]
well sorry creating a project beforehand fixed my issue.
