### ISSUE TITLE
Replace vulnerable package

### ISSUE THREAD

**Issue by jamesone** [getsentry/sentry-wizard#15]
Package in question: `open@0.0.5`
> This package is not being actively developed and was last published 4 years ago.

Security issue: https://nodesecurity.io/advisories/663
Alternative package: https://github.com/sindresorhus/opn

**Comment by A-Tokyo** [comment]
Confirmed using https://snyk.io/

**Comment by HazAT** [comment]
Thanks for reporting this but this has already been fixed in `0.10.1` patch release
https://github.com/getsentry/sentry-wizard/releases/tag/v0.10.1
