### ISSUE TITLE
Skip Sentry connect variable

### ISSUE THREAD

**Issue by ewal** [getsentry/sentry-wizard#16]
I'm trying to configure Sentry in my ci service. I've set the `SENTRY_WIZARD_SKIP_CONNECT` environment variable to `true` but I get the following result:

```
    "sentryCli": {
        "argv": {
            "_": [],
            ...
            "debug": true,
            "skip-connect": false,
            "skipConnect": true,
            ...
```
I assume the variable isn't translated correctly. Kinda stuck with the configuration currently :)

**Comment by HazAT** [comment]
Oh, fixing this, gimme a sec.
