### ISSUE TITLE
Sentry on Next.js - Stuck on "Waiting for wizard to connect"

### ISSUE THREAD

**Issue by AlessandroVol23** [getsentry/sentry-wizard#166]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
version: 1.2.17 | sentry-cli version: 1.74.4
Next 12.1.6

### Steps to Reproduce

1.  `yarn add @sentry/nextjs`
2. `npx @sentry/wizard -i nextjs`
3. Browser opens
<img width="1730" alt="image" src="https://user-images.githubusercontent.com/19362086/168965062-1a951a97-8d18-4cd8-9ec5-c254899b0712.png">

### Expected Result

What you thought would happen.
Sentry will connect

### Actual Result

No errors and no connection to sentry
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/19362086/168965128-aae6d4c4-1084-41d2-975e-597fba6040d9.png">

**Comment by boringContributor** [comment]
+1 can confirm.

**Comment by reymon359** [comment]
Hey @boringContributor  @AlessandroVol23 did you find a way to solve this? I am facing the same issue
