### ISSUE TITLE
Error when running the @sentry/wizard script

### ISSUE THREAD

**Issue by ruanblima** [getsentry/sentry-wizard#167]
I am trying to set up sentry in my react native project. But when I try to execute the script "npx @sentry/wizard -i reactNative -p ios android" this error occurs

### Environment

Node
v16.13.0

React native
"react-native": "0.63.4",

Sentry
"@sentry/react-native": "^3.4.2",

### Steps to Reproduce

1. Execute the command

### Actual Result

![image](https://user-images.githubusercontent.com/57442366/170404857-e013b980-bef0-4362-acd8-91f2b28a5424.png)

![image](https://user-images.githubusercontent.com/57442366/170404896-cc5865cb-3b84-4b5e-a53e-8ba1daf2f05b.png)

**Comment by lobsterkatie** [comment]
@ruanblima Can you give the full stacktrace of the error, please? It's hard to say why it's not finding a module without knowing what module it is and what code is trying to load that module.

**Comment by ruanblima** [comment]
![image](https://user-images.githubusercontent.com/57442366/177003094-35349fee-3def-435a-960e-cb90dc2ef1a7.png)

**Comment by ruanblima** [comment]
> ![imagem](https://user-images.githubusercontent.com/57442366/177003094-35349fee-3def-435a-960e-cb90dc2ef1a7.png) @lobsterkatie

**Comment by lobsterkatie** [comment]
@marandaneto - Do you have theories here? Is `escalade` something we use?

**Comment by marandaneto** [comment]
@lobsterkatie no idea, but apparently `escalade` is a dependency of `yargs`.
@ruanblima have you tried using a more recent version of `node`?
have you tried to clean the `node_modules` and install it again?
it does not seem related to Sentry itself.

**Comment by marandaneto** [comment]
@ruanblima any news here?

**Comment by DrewWeth** [comment]
Any updates?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by ngvcanh** [comment]
I have a mono repo project for React Native.
When I run wizard, I shown error:

```
Sentry Wizard failed with:
Command failed: yarn add @sentry/react-native
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).


Protip: Add --debug to see whats going on
OR use --help to see your options
```

I tried again with a few commands to ignore the workspace

```
npx @sentry/wizard -s -i reactNative -W
npx @sentry/wizard -s -i reactNative -- -W
```

But it's not work
How can I do that?

Thanks
