### ISSUE TITLE
How to set default project via CI

### ISSUE THREAD

**Issue by bawantha** [getsentry/sentry-wizard#171]
I'm running sentry-wizard in the CI pipeline, However, while building it asks me to select project via keyboard can I set it default?
![Screenshot 2022-06-24 at 12 28 10](https://user-images.githubusercontent.com/17080593/175489542-745d5686-1f7f-4a81-8472-0898159d91ba.png)

**Comment by grossadamm** [comment]
@bawantha 

If you sent sentry.properties manually you can use `--quiet --skip-connect` together

https://github.com/getsentry/sentry-wizard/issues/192
