### ISSUE TITLE
Race condition in tests "Cannot log after tests are done."

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-wizard#186]
### Environment

When I add a `console.log` in `ReactNative` integration, the tests will fail because the `console.log` would be called after the tests are supposedly done. It's not related to ReactNative test added in https://github.com/getsentry/sentry-wizard/pull/185 the issue was there before only not discovered.

### Steps to Reproduce

1. Add `console.log` in `ReactNative` integration.
2. Run `yarn test`

### Expected Result

The test should finish successfully with the `console.log` in-between the test output.

### Actual Result

![Screenshot 2022-08-29 at 15 50 31](https://user-images.githubusercontent.com/31292499/187216781-ce5d4fb9-41dd-417c-8384-700a833666cc.png)

**Comment by Lms24** [comment]
Currently going through old wizard issues.
@krystofwoldrich is this still happening/relevant? A log shouldn't happen after the test finishes. This is weird indeed.

**Comment by krystofwoldrich** [comment]
@Lms24 Seems to fix now. Thanks for the ping.
