### ISSUE TITLE
Skip wizard if already configured?

### ISSUE THREAD

**Issue by emilkarl** [getsentry/sentry-wizard#19]
Using react-native-sentry which has a post-install hook which triggers the wizard. Is there some way to make the wizard understand that its already configured and skip the whole process? 

https://github.com/getsentry/react-native-sentry/issues/465

**Comment by HazAT** [comment]
Hmm, the wizard should check if the file is there already and not run again.
I will take a look, what's going on.

**Comment by emilkarl** [comment]
@HazAT Let me know if you need more background, I posted more info in the issue linked in the first message.

**Comment by emilkarl** [comment]
Have you had time to look at this @HazAT. Super annoying to have to reset the file every time. :(

**Comment by azai91** [comment]
Agreed. Any update on this?

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
