### ISSUE TITLE
[React Native] Setup not working properly for iOS when using Swift

### ISSUE THREAD

**Issue by jfmlima** [getsentry/sentry-wizard#2]
I've went through the react-native integration since I couldn't manage to get it to work in my react-native project and apparently the wizard only works when the AppDelegate is in objC.

Even if I try to add the code myself it still doesn't work.
I was wondering if you could update the wizard to work with Swift.
And also, are we supposed to do pod install after linking? or is the wizard supposed to do that?

Thanks in advance.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
