### ISSUE TITLE
'debug' is defined but never used

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-wizard#200]
Found by https://github.com/getsentry/sentry-wizard/pull/199/files
Should I just remove `debug` from import? I don't know the codebase so asking before doing it.

<img width="809" alt="Screenshot 2022-10-17 at 13 45 53" src="https://user-images.githubusercontent.com/5731772/196169050-555d9e77-876f-4a8f-9379-8fc8370fc5d6.png">

**Comment by Lms24** [comment]
Gonna close this as part of an issue cleanup. RE `debug`: `debug` is currently still used in two places:

![image](https://github.com/getsentry/sentry-wizard/assets/8420481/2bb3f7fa-2fab-41c6-89bd-98af5a4948e9)

Side note:
We're slowly moving away from the old class-based wizard to new, simplified wizards (e.g. next, sveltekit, sourcemaps, ios, android). There we have a dedicated `debug` function. Our goal is to eventually remove the old class based architecture, meaning the Logging file will eventually be gone.
