### ISSUE TITLE
[@sentry/cli] Path resolution to `@sentry/cli` is unreliable

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry-wizard#208]
As reported by Cramer, following our stock nextjs SDK instructions to use the wizard through `npx` led to `@sentry/cli` being resolved to `../../.npm/_npx/a8388072043b4cbc/node_modules/@sentry/cli/bin/sentry-cli` rather than the copy installed in the project's `node_modules` folder. (This then gets inserted in the `sentry.properties` file the wizard generates.)

- [ ] Figure out why this is happening
- [ ] Perhaps first decide if we even need to include the path to the executable in `sentry.properties` when dealing with `@sentry/cli`. It should download the binary to a standard place, so we might not need this at all.

**Comment by smeubank** [comment]
@kamilogorek this something you might have an idea about off the top of your head?

**Comment by lobsterkatie** [comment]
Related: https://github.com/getsentry/sentry-cli/issues/915

**Comment by lobsterkatie** [comment]
Per @kamilogorek  in slack:

> fwiw `npx` doesnt install its traasnsitive dependencies locally, so as long as someone has `NODE_PATH` set to follow their `volta/yarn/npm/whatever` node_modules, it will never work, due to `@sentry/cli` being installed inside `.npx` directory

`@sentry/cli` should be installed as a dependency of `@sentry/nextjs`. We’re working on making it not a dependency of the wizard: https://github.com/getsentry/sentry-wizard/issues/201.

**Comment by vladanpaunovic** [comment]
Fixed in release https://github.com/getsentry/sentry-wizard/releases/tag/v2.3.1

Thanks @timfish!
