### ISSUE TITLE
RN: Guide user on How to patch App.js if file not found

### ISSUE THREAD

**Issue by taehyun-kim-tenuto** [getsentry/sentry-wizard#226]
### Environment

What version are you running? Etc.

"react native": "0.69.7"
"@sentry/react-native": "^4.13.0",
"@sentry/wizard": "^2.4.1",

### Steps to Reproduce

1. What
2. you
3. did.

i have to self host so i wrote sentry-wizard --url mySentryUrl

and this log came out

✅ Patched build.gradle file.
🚨 Could not find index.android.@(j|t|cj|mj)s?(x) nor App.@(j|t|cj|mj)s?(x) files.
❓ Please, visit https://docs.sentry.io/platforms/react-native
✅ Added sentry.properties file to android
Successfully set up android for react-native
✅ Patched build script in Xcode project.
🚨 Could not find index.ios.@(j|t|cj|mj)s?(x) nor App.@(j|t|cj|mj)s?(x) files.
❓ Please, visit https://docs.sentry.io/platforms/react-native
✅ Added sentry.properties file to ios
Successfully set up ios for react-native

🎉  Successfully set up Sentry for your project 🎉

is it done well?
whats the meaning of the log??
🚨 Could not find index.ios.@(j|t|cj|mj)s?(x) nor App.@(j|t|cj|mj)s?(x) files.

### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by marandaneto** [comment]
We're going to make the error message clearer.
