### ISSUE TITLE
One line `@sentry/react-native` install

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-wizard#236]
Replicate https://github.com/getsentry/sentry-wizard/pull/219 for RN.

Steps that are missing in RN at the moment:
- Install the npm package `@sentry/react-native` [#219](https://github.com/getsentry/sentry-wizard/pull/219)
- Auto create project at Sentry [#219](https://github.com/getsentry/sentry-wizard/pull/219)
- Run pod-install for iOS. (new)

**Comment by kahest** [comment]
Effort is small, impact is small

**Comment by kahest** [comment]
elevated prio, we wanna tackle this soon
