### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by IronTony** [getsentry/sentry-wizard#24]
Hi,

I downloaded the package, but when I try to execute it, I receive this error:
`zsh: command not found: sentry-wizard`

I am on MacOS, can you please help me?
Thank you in advance

**Comment by jan-auer** [comment]
Did you install it globally and is your path configured correctly?

```
yarn global add @sentry/wizard
npm install -g @sentry/wizard
```

**Comment by IronTony** [comment]
Thank you, my fault!
