### ISSUE TITLE
Dogfood sentry-wizard

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#242]
### Background
Similar to [sentry-unplugin](https://github.com/getsentry/sentry-javascript-bundler-plugins) work we will be able to monitor it in Sentry. This allows us to check the performance and tracing of our own product.

[sentry-unplugin Sentry project](https://sentry.io/organizations/sentry/performance/?project=6690737)

### Outcomes:
- able to track quantity of usage
- able to detect any performance issues
- able to trace the different services (projects) involved with upload of source maps
  - trace propagation must be strictly controlled to only Sentry services

### Requirements:
- a new project in Sentry org (if not existing)
- Bare minimum transactions to be sent to that project 
- Ideally we could have transactions based on flows as a proposal to see which flows are used the most
  - open to other proposals like tags or custom metrics
- we should be able to differentiate between CI or test stage transaction and what is sent from production environment
- strip down what is sent to Sentry to a bare minimum to reduce all risk of any PII sent to Sentry

**Comment by Lms24** [comment]
Closing as this is superseded by #411 (or already included in a few wizards).
