### ISSUE TITLE
sentry-symbols.js doesn't conform to strict mode

### ISSUE THREAD

**Issue by aguynamedben** [getsentry/sentry-wizard#27]
I added sentry-symbols.js to my project, and [this line](https://github.com/getsentry/sentry-wizard/blob/master/scripts/Electron/symbols.js#L17) causes our linter (ESLint) to fail with `Parsing error: package is a reserved word in strict mode`. This seems like a Babel parsing issue, not an ESLint configuration issue—it seems that [Babel's default is to use strict mode](https://stackoverflow.com/questions/33821312/how-to-remove-global-use-strict-added-by-babel). I can't find an easy way to tell Babel "it's okay for this single file to not use strict mode".

It's extra annoying because we have our linting pretty refined, and there's not a workaround other than going off-happy-path and renaming the variable ourselves.

**Comment by jan-auer** [comment]
Thanks for this report, @aguynamedben. Would it be possible to just exclude the entire file from linting on your end? Of course, we can just disable ESlint completely for this entire file.

In the long run, I think this fuctionality should become part of the wizard and not a file it generates (cc @HazAT)

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Comment by aguynamedben** [comment]
This is fine. We just manually edited sentry-symbols.js after the wizard created it...

```js
#!/usr/bin/env node

/* eslint-disable */
// Source: https://github.com/getsentry/sentry-wizard/blob/master/scripts/Electron/symbols.js

let SentryCli;
let download;

// ...rest of file...
```
