### ISSUE TITLE
react-native Add SAGP to the Android application

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-wizard#287]
For some features, we offer on the Android platform, Sentry Android Gradle Plugin is needed. At the moment our RN users have to add this plugin manually.

https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#enable-sentry-agp

Users need to add the following to their `android/app/build.gradle`

```diff
+ apply plugin: "io.sentry.android.gradle"

import com.android.build.OutputFile

+ sentry {
+     // Disables or enables the automatic configuration of Native Symbols
+     // for Sentry. This executes sentry-cli automatically so
+     // you don't need to do it manually.
+     // Default is disabled.
+     uploadNativeSymbols = true
+ 
+     // Does or doesn't include the source code of native code for Sentry.
+    // This executes sentry-cli with the --include-sources param. automatically so
+     // you don't need to do it manually.
+     // Default is disabled.
+     includeNativeSources = true
+ }
+ 
+   / `@sentry/react-native` ships with compatible `sentry-android`
+   // This option would install the latest version that ships with the SDK or SAGP (Sentry Android Gradle Plugin)
+   // which might be incompatible with the React Native SDK
+   // Enable auto-installation of Sentry components (sentry-android SDK and okhttp, timber and fragment integrations).
+   // Default is enabled.
+   autoInstallation {
+     enabled = false
+   }
```

and the following to their `android/build.gradle`
```diff
buildscript {
    dependencies {
+        classpath("io.sentry:sentry-android-gradle-plugin:3.4.2")
    }
}
```

This could be done by the wizard.

**Comment by focux** [comment]
I'm not sure if this is the right place to report this but took me a bit to add SAGP to my RN app because the docs that you linked above don't mention anything about adding the `classpath("io.sentry:sentry-android-gradle-plugin:3.4.2")`.

**Comment by krystofwoldrich** [comment]
@focux The mentioned docs page links to the SAGP docs page, but you are right, we can add this right to the React Native SAGP page. Thank you for the feedback.

**Comment by krystofwoldrich** [comment]
Should also upload proguard files.
Verify that sentry.properties are used correctly but the SAGP (does the token has the right permission).
