### ISSUE TITLE
Does not correctly patch index.js

### ISSUE THREAD

**Issue by matt-oakes** [getsentry/sentry-wizard#3]
NEw React Native projects now have a single `index.js` file instead of an `index.ios.js` and `index.android.js` file. The automated setup does not correctly patch this shared index file.

**Comment by HazAT** [comment]
Hey, don't they have `App.js`?

**Comment by matt-oakes** [comment]
Actually, you're right... For some reason my project has an index.js file. I must have manually changed something myself. Sorry about that.

**Comment by HazAT** [comment]
No worries 😅 
I was just asking because the facebook guys are constantly changing so much stuff that this could have actually been the case.
