### ISSUE TITLE
Next.js 13 app router + @sentry/wizard breaks typing

### ISSUE THREAD

**Issue by trbarton** [getsentry/sentry-wizard#307]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/nextjs

### SDK Version

7.56.0

### Framework Version

13.4.5

### Steps to Reproduce

This bug appears in a Next 13 app router project using typescript and the App router exclusively. 

Create a project and set up a dynamic route in the app directory. e.g. app/post/[id]/page.tsx
On the new page use the useParams() hook from next/navigation to get the id 
`const { id } = useParams();`
This currently will be typed as a string. Running the build command should also be successful

Now run the sentry wizard as per the Sentry next.js setup instructions: 
`npx @sentry/wizard@latest -i nextjs`

Now building will fail due to a type error. This is due to the wizard creating a test route in the pages directory.
We now have both a pages and app directory so next/navigation uses the "compat" types. id is no longer of type string
but instead is of type: Record<string, string, string[]> | null

This caveat should probably be documented in the Next.js setup instructions

### Expected Result

An app router project to build successfully after running the sentry wizard

### Actual Result

![image](https://github.com/getsentry/sentry-javascript/assets/9353052/4e0b91f7-54a9-4c42-86cc-59e51697e7cb)

**Comment by mayank1513** [comment]
Have created PR fixing this issue - https://github.com/getsentry/sentry-wizard/pull/385
