### ISSUE TITLE
Android cli-wizard

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#316]
### Background:

Success rates for developers creating Android projects and sending events, are low in comparison to other platforms. We want to ship a number of improvements to address this and try to help android devs navigate setting up their Android apps with Sentry. This issue will focus on shipping a cli-wizard

### Solution Proposal:

At first this wizard is really only intended for setting up Android apps which do not have any Sentry configuration yet, However the wizard should recognize if there is existing config, in the future it may be desirable to update existing. For now we will ignore this complexity.

Goal: Make it exceedingly easy for users to get started with Sentry on Android

`brew @sentry/wizard@latest -i android`

**Login:**
- add a one line wizard command to setup an android application with Sentry SDK and potentially build tool plugins

**Install:**
- Wizard would need to have logic to detect (Groovy vs Kotlin)

**Configure:**
- Need to detect `AndroidManifest.xml` to inject needed config options
- SDK init should include GA top product enabled options (Errors & Performance)

**Verify:**
- [nice to have] an error page equivalent to easily allow the user to test the setup

**Build tooling:**
- [nice to have +]

#### Requirements

- user can run a one liner in their terminal to trigger flow
- User prompted to login or create account
  - existing get's list of existing projects
  - create back to terminal with created project in list   
- user receives all keys, tokens, and variables required to create releases and upload source maps to sentry
- user app is injected with a script which run sentry-cli commands with all proper inputs (these could be provided already by bundlers)
- user receives log statements which simply state what was attempted (succeeded and/or failed), then what they should do next (docs, manual merge, copy/paste, yarn run build)

### Reference:

- react-native wizard: `npx @sentry/wizard@latest -s -i reactNative`
  - https://github.com/getsentry/sentry-wizard/issues/280
- NextJS: `npx @sentry/wizard@latest -i nextjs`
- SvelteKit: `npx @sentry/wizard@latest -i sveltekit`
- Delivery approach for source maps for JS: https://github.com/getsentry/team-sdks/issues/16
- https://github.com/getsentry/team-mobile/issues/26

**Comment by Lms24** [comment]
Just out of curiosity: Do Android developers use `npm/npx`? Just wondering if executing this command is as seamless for Android devs as for JS/web devs 😅

**Comment by smeubank** [comment]
> Just out of curiosity: Do Android developers use `npm/npx`? Just wondering if executing this command is as seamless for Android devs as for JS/web devs 😅

we discussed this with mobile folks, and the agreement was that many android devs might have node, but the best approach would probably be to publish to `brew` and mobile devs install and run from there

**Comment by smeubank** [comment]
> things to check before getting started with this in JS:
>  - can we easily modify manifest files in the correct place using JS?
>  - can we easily modify gradle config files
>  - can we easily modify Java Code
> 
> other alternatives that come to mind:
>  - allow config from gradle plugin and pass them into the app
>  - add init from gradle plugin automatically
>  - add a login flow to gradle; could work likes this
>  - you add our plugin to your gradle project
>  - you then invoke some gradle task ./gradlew sentryLogin that prompts you for credentials and somehow modifies files or at least spits out what to put where
