### ISSUE TITLE
SvelteKit: Use `abort` to exit the wizard on error

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-wizard#337]
While reviewing #334 I realized that our SvelteKit wizard doesn't exit with an error code in case we reach an error state. Instead we currently just return which will make the wizard exit with a success message. 
To fix this, we should just use `abort` from our clack-utils. 
Furthermore, once we add telemetry, this will ensure that we flush out the running transaction before exiting.

**Comment by bfontaine** [comment]
This is probably why I got this:
```
…
│
■  Error while setting up the SvelteKit SDK:
│
●  TypeError: 'set' on proxy: trap returned falsish for property 'plugins'

🎉  Successfully set up Sentry for your project 🎉
```
There was an error, but I still got a success message.
(version 3.7.1)
