### ISSUE TITLE
iOS Wizard Telemetry

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#343]
To ensure we can track that the wizard is working well, and so that we can identify patterns we want to collect some telemetry data from the wizard. This will also allow us to get insights to improve the DX of the wizard flow

Example tags: 
Does not need to be limited to this

  "tags": [
    ["added-env-var-to-ci", "True"],
    ["already-has-sentry-account", "True"],
    ["environment", "production"],
    ["has-promo-code", "False"],
    ["initial-sdk-version", ">=7.47.0"],
    ["integration", "sourcemaps"],
    ["level", "info"],
    ["node", "v16.14.2"],
    ["opened-wizard-link", "True"],
    ["platform", "win32"],
    ["project", "portal-frontend"],
    ["runtime", "node v16.14.2"],
    ["runtime.name", "node"],
    ["selected-tool", "webpack"],
    ["self-hosted", "False"],
    ["release", "3.5.0"],
    ["user", "id:offerfit"],
    ["transaction", "sentry-wizard-execution"],
    ["url", "https://sentry.io/"]
  

See the [Sentry Wizard Dashboard](https://sentry.sentry.io/dashboard/53706/?project=4505425820712960&query=wizard&statsPeriod=14d) for more insights

We are not interested in collecting any PII about the individual users! Please check existing implementation for best practices 🙏

**Comment by kahest** [comment]
@smeubank is this also relevant for [Android](https://github.com/getsentry/sentry-wizard/issues/316)?

**Comment by brustolin** [comment]
This was done with #334
