### ISSUE TITLE
Sentry Wizard available via brew

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#346]
Developers on some platforms may be more comfortable working with brew, vs npm/npx/node.

The `@sentry/wizard` should be available via brew

The [sentry-cli is already for example](https://github.com/getsentry/homebrew-tools/blob/master/Formula/sentry-cli.rb).

**Comment by markushi** [comment]
Would be interesting to see how dominant brew is on non-Mac platforms like Windows, Linux.

**Comment by kahest** [comment]
initial PR on brew: https://github.com/getsentry/homebrew-tools/pull/6
next up: automate publishing via craft
