### ISSUE TITLE
SvelteKit wizard fails to add `sentrySvelteKit` plugin in vite configs that don't directly default-export the config

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-wizard#362]
### Environment

What version are you running? Etc.

### Steps to Reproduce

1. Clone [turborepo svelte example](https://github.com/vercel/turbo/tree/main/examples/with-svelte)
2. Run wizard

### Expected Result

Wizard successfully adds `sentrySvelteKit` plugin to `vite.config.js`

### Actual Result

Wizard fails at `vite.config.js` injection with error

```
■  Error while setting up the SvelteKit SDK:
│
●  TypeError: 'set' on proxy: trap returned falsish for property 'plugins'
```

Probably some problem with `magicast`. Need to investigate further

### Update

This isn't directly related to turborepo but to the structure of the `vite.config.js`. Explanation: https://github.com/getsentry/sentry-wizard/issues/362#issuecomment-1643852328

**Comment by Lms24** [comment]
Discovered in https://github.com/getsentry/sentry-javascript/issues/8325

**Comment by happysalada** [comment]
Just got this exact same error.
For other people coming in, it looks like the step that is missing is the modification of the svelte.config.js file. So this is just a problem with sourcemaps, the rest should work fine.

**Comment by Lms24** [comment]
> it looks like the step that is missing is the modification of the vite.config.js file

Yes, that's correct. The setup for vite is very simple though. As a workaround I suggest [following code snippet](https://docs.sentry.io/platforms/javascript/guides/sveltekit/manual-setup/#vite-setup)

I believe I identified the issue:

Currently, we can only handle adding the plugin if the config export is directly exported:

```js
export default {
  // config object...
}
```

Apparently, `magicast`, the library we use for this modification, doesn't yet handle other typical config options like

```js
const config = {...}
export default config;
```

We should add this; probably help Antfu out and contribute upstream.

Regardless, we'll also provide a fallback copy/paste snippet directly in the wizard if we encounter an error so that we can always help out directly in the wizard.

Will fix this soon.

**Comment by Lms24** [comment]
I opened https://github.com/unjs/magicast/pull/69 to fix this upstream in `magicast`. I'll give the maintainers a few days to respond. In the meantime, I'll work on the fallback mechanism to provide copy/paste instructions if we fail to modify the vite config AST.
