### ISSUE TITLE
Debug output is not verbose enough

### ISSUE THREAD

**Issue by bfontaine** [getsentry/sentry-wizard#375]
Hello,
Running `npx @sentry/wizard@latest -i sveltekit` (wizard 3.7.1), I get this output:

```
...
■  Error while setting up the SvelteKit SDK:
│
●  TypeError: 'set' on proxy: trap returned falsish for property 'plugins'

🎉  Successfully set up Sentry for your project 🎉
```

Running it again with `--debug`, I get:
```
...
■  Error while setting up the SvelteKit SDK:
│
●  TypeError: 'set' on proxy: trap returned falsish for property 'plugins'

{
	"integration": {
		"_argv": {
			"_": [],
			"i": "sveltekit",
			"integration": "sveltekit",
			"debug": true,
			"uninstall": false,
			"skip-connect": false,
			"skipConnect": false,
			"quiet": false,
			"s": false,
			"signup": false,
			"disable-telemetry": false,
			"disableTelemetry": false,
			"$0": "../../../.npm/_npx/ddb126e78325956c/node_modules/.bin/sentry-wizard"
		},
		"_isDebug": true
	}
}


🎉  Successfully set up Sentry for your project 🎉
```

The `--debug` option didn’t add any output that could help me debug the issue.

(the error itself is tracked in https://github.com/getsentry/sentry-wizard/issues/362 and the bug of the success message that shows even when there’s an error is tracked in https://github.com/getsentry/sentry-wizard/issues/337)

**Comment by Lms24** [comment]
Closing as #381 was merged and will be released with the next version soon
