### ISSUE TITLE
Is this work with Simple React App build with CRA not Next.js

### ISSUE THREAD

**Issue by ukhanzada-nisum-com** [getsentry/sentry-wizard#377]
Is this work with Simple React App built with CRA, not Next.js? If not do we have any plans in the near future?

**Comment by AbhiPrasad** [comment]
Hey @ukhanzada-nisum-com - we try to autodetect `create-react-app` here: https://github.com/getsentry/sentry-wizard/blob/f660430660f942470fb87dadce0f9695dc10dbb7/src/sourcemaps/utils/detect-tool.ts#L11C1-L11C1

You'll have to follow the instructions in https://docs.sentry.io/platforms/javascript/guides/react/ to set up the SDK, but you can configure sourcemaps uploading with `npx @sentry/wizard@latest -i sourcemaps`
