### ISSUE TITLE
wizard crashes on project with no build phases

### ISSUE THREAD

**Issue by dgobaud** [getsentry/sentry-wizard#38]
![image](https://user-images.githubusercontent.com/240811/66512274-7114fd00-ea8d-11e9-9e31-2b6ce04f4346.png)

![image](https://user-images.githubusercontent.com/240811/66512285-770ade00-ea8d-11e9-9cb4-85aac9ae62d1.png)

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
