### ISSUE TITLE
iOS Wizard improvements

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-wizard#399]
```[tasklist]
### Must have
- [x] resolve `SENTRY_AUTH_TOKEN` from env/variable, don't inject directly into the build phase script/fastfile
- [x] better handling of project directory name is not same as `.xcodeproj` filename (TBD how to handle multiple platform  folders, e.g. iOS, tvOS, watchOS,...)
```

```[tasklist]
### Nice to have
- [ ] better/more verbose log output of changes (e.g. "patching project file", "adding init snippet", etc.)
- [ ] if a project uses SPM and CocoaPods, ask user which to use instead of defaulting to CocoaPods
- [ ] resolve `DSN` from env/variable instead of injecting it directly into the init snippet
```

**Comment by kahest** [comment]
cc @smeubank @brustolin

**Comment by brustolin** [comment]
> better handling of project directory name is not same as `.xcodeproj` filename

Im not sure that I understand this. Can you give me an example please?

**Comment by kahest** [comment]
> > better handling of project directory name is not same as `.xcodeproj` filename
> 
> Im not sure that I understand this. Can you give me an example please?

as discussed on another channel, many projects don't follow the pattern that the "main" iOS project sources are located in a directory that is called the same as the `.xcodeproj` file (e.g. `MyShinyApp.xcodeproj` might place project sources for their iOS & watchOS apps in `/MyShinyApp-iOS` and `/MyShinyApp-watchOS`)

**Comment by romtsn** [comment]
@brustolin should we close this after your recent improvements, or is there something else left to implement?

**Comment by brustolin** [comment]
This is done with last iOS improvements.
