### ISSUE TITLE
Add telemetry to other SDK wizards

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#411]
There are a number of existing wizard flows for setting up SDKs where we should collect telemetry to track usage and identify room for improvement.

```[tasklist]
- [x] Remix (already included in intial wizard release)
- [ ] https://github.com/getsentry/sentry-wizard/issues/451
- [ ] https://github.com/getsentry/sentry-wizard/issues/450
- [ ] #365
- [ ] Cordova
- [ ] Electron
```

Collect data similar to source maps wizard, and speciics on what was successful or failed with specific to each of the above. Setting up client, server, and bundler config.

see related react-native [issue](https://github.com/getsentry/sentry-wizard/issues/365) and source maps implentation for more details

**Comment by Lms24** [comment]
For anyone building dashboards: Once the next wizard release is out, we can filter on `environment-[wizardName]` to distinguish sessions and transactions from individual wizards (#413).

**Comment by Lms24** [comment]
Some thoughts around adding telemetry to older wizards: https://github.com/getsentry/sentry-wizard/issues/365#issuecomment-1721072034

**Comment by Lms24** [comment]
Closing as for now we're happy with the state of telemetry in the wizards
