### ISSUE TITLE
feat: add option for quasar+vite support 

### ISSUE THREAD

**Issue by pharindoko** [getsentry/sentry-wizard#431]
I`m using quasar with vite.
The vite part can be found in quasar.config.js

It would be nice to have the option to select Quasar+Vite.

**Comment by Lms24** [comment]
Hi @pharindoko thanks for writing in!

Well, TIL about Quasar 😅 

Just to confirm, we're talking about the sourcemaps wizard (i.e. `npx @sentry/wizard@latest -i sourcemaps`), correct?

I don't think that we're going to special-case framework in the wizard at this time, given that we don't officially support it with our SDK. IIUC quasar builds on top of Vue so you're using our Vue SDK? 

For future reference, I believe you're talking about [this config file](https://quasar.dev/quasar-cli-vite/developing-capacitor-apps/configuring-capacitor#quasar-config-file), correct? And the structure of the vite config looks like the one we see in the bottom snippet?

If you wanna take a stab at implementing a flow for Vite+Quasar, PRs are welcome! (However, I can't guarantee that we'll get to merge this soon).

I'm gonna close this issue for the time being but feel free to ping me if you think this should be reopened.

**Comment by pharindoko** [comment]
> Hi @pharindoko thanks for writing in!
> 
> Well, TIL about Quasar 😅
> 
> Just to confirm, we're talking about the sourcemaps wizard (i.e. `npx @sentry/wizard@latest -i sourcemaps`), correct?
> 
> I don't think that we're going to special-case framework in the wizard at this time, given that we don't officially support it with our SDK. IIUC quasar builds on top of Vue so you're using our Vue SDK?
> 
> For future reference, I believe you're talking about [this config file](https://quasar.dev/quasar-cli-vite/developing-capacitor-apps/configuring-capacitor#quasar-config-file), correct? And the structure of the vite config looks like the one we see in the bottom snippet?
> 
> If you wanna take a stab at implementing a flow for Vite+Quasar, PRs are welcome! (However, I can't guarantee that we'll get to merge this soon).
> 
> I'm gonna close this issue for the time being but feel free to ping me if you think this should be reopened.

Thanks for the reply

No I don`t wanna implement this - no time.
But I guess I figured it out how to implement it into quasar to upload the sourcemaps to sentry and I want to show it here if somebody has the same question ...


in **quasar.config.js**:

      vitePlugins: [
        [
          // Put the Sentry vite plugin after all other plugins
          require('@sentry/vite-plugin').sentryVitePlugin, {
            url: 'https://sentry.io/',
            debug: true,
            sourcemaps: true,
            release: revision,
            org: 'test',
            project: 'test-frontend',
            authToken: process.env.SENTRY_AUTH_TOKEN,
            silent: false,
            revision: revision,
          }
        ],
      ],
    },

**Comment by pharindoko** [comment]
we can close this :)
