### ISSUE TITLE
Wizard updated build command incorrectly in Node.js environment

### ISSUE THREAD

**Issue by whitep4nth3r** [getsentry/sentry-wizard#457]
Hello! 👋🏼

### Environment

Node: 18.17.1
npm: 9.6.7

Excerpt of package.json before running command:

```
  "scripts": {
    "test": "jest",
    "start": "node build/src/app.js",
    "build": "tsc",
    "dev": "nodemon",
    "heroku-prebuild": "...",
    "heroku-postbuild": "...;",
  },
```

### Steps to Reproduce

1. Run `npx @sentry/wizard@latest -i sourcemaps` in project root
2. Choose mainly default options using the wizard (nothing untoward)
3. Confirmed I wanted the wizard to update my build command to run the sourcemaps command during build
4. No errors were provided during the process

### Expected Result

The build command in package.json to be updated to:

`tsc && npm run sentry:sourcemaps` 

### Actual Result

The build command in package.json was updated to:

`tsc && [object Object] run sentry:sourcemaps` 

![image](https://github.com/getsentry/sentry-wizard/assets/52798353/9276f4fb-325b-4914-9bc5-12c81d0339b1)

**Comment by Lms24** [comment]
Hi, this was already fixed in #453 and will be released soon. Thx for reporting :)

**Comment by whitep4nth3r** [comment]
I searched for 'object' but I didn't see this in the issues, should have checked for PRs. 😅

Thank you!

**Comment by Lms24** [comment]
aaand it's out: https://github.com/getsentry/sentry-wizard/releases/tag/v3.13.0 🎉
