### ISSUE TITLE
Error in Sentry upload  (app:bundleReleaseJsAndAssets_SentryUpload FAILED)

### ISSUE THREAD

**Issue by suraj2122** [getsentry/sentry-wizard#46]
I get the following build error **app:bundleReleaseJsAndAssets_SentryUpload FAILED** when I updated my react native app with latest sentry library, So i removed **cli.executable** line under android/sentry.properties file. Now the builds start working , So this is the correct fix ? 

Please help us regarding this

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
