### ISSUE TITLE
Add `@sentry/cli` to package.json to `trustedDependencies` when using bun

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-wizard#476]
The wizard should add `@sentry/cli` to package.json trusted dependencies. https://bun.sh/docs/cli/install#trusted-dependencies when using Bun as a package manager.

See https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/412

_Originally posted by @AbhiPrasad in https://github.com/getsentry/sentry-wizard/issues/446#issuecomment-1733781289_

**Comment by Lms24** [comment]
I believe we should be good to adjust this in our package installation helper function.

**Comment by Lms24** [comment]
Further investigation: transitive dependencies are _not_ affected by setting their parent in  `trustedDependencies` ([source](https://bun.sh/guides/install/trusted)). Meaning, if the install command is to add `@sentry/vite-plugin`, adding it to `trustedDependencies` is not going to enable the postinstall script of `@sentry/cli`. Meaning, we'll most likely have to create an index of packages that somewhere downstream require `@sentry/cli`, check it before installing, if required, add `@sentry/cli` to `trustedDependencies` and run the actual install command.

Also, on the same page:

![image](https://github.com/getsentry/sentry-wizard/assets/8420481/9c92cc39-d76e-45bf-b696-a8ac82a72b00)

I wonder if `@sentry/cli` would qualify for this list.

**Comment by chargome** [comment]
@Lms24 do we still need to do this? According to https://github.com/getsentry/sentry-wizard/issues/446 this should work right?

**Comment by Lms24** [comment]
Yeah let's close this and re-open if necessary. Thanks for the tag!
