### ISSUE TITLE
Slight Text Tweak for the Next.js Sentry Setup Wizard

### ISSUE THREAD

**Issue by ingridkindem** [getsentry/sentry-wizard#480]
Hey team 👋,

First off, major kudos on the Sentry setup wizard for Next.js. I was practically gliding through that setup—it's some top-tier devex right there! 🚀

That said, I did hit a teeny hiccup. Here's the deets:

**Current Text:**
```javascript
${chalk.cyan(
  'You can validate your setup by starting your dev environment (`next dev`) and visiting "/sentry-example-page".',
)}
```

**Proposed Text:**
```javascript
${chalk.cyan(
  'You can validate your setup by restarting your dev environment (`next dev`) and visiting "/sentry-example-page".',
)}
```

Why the change? Well, after setting up, I eagerly awaited the sentry events like a kid on Christmas morning, but Santa didn't come. In other words, no events was being sent to Sentry. After a solid hour of shotgun debugging, I realised the issue: changes in the Next.js config don't take effect until the server is restarted. 🫠 I didn't start the dev environment, because it was already running.

Such a minor text update could potentially spare others the detective work I had to dive into.

Thanks for the hard work, and let's make this tiny but significant enhancement! 💅

**Comment by Lms24** [comment]
Hi @ingridkindem thanks for writing in and thanks for the kind words! 

This is a great observation and you're totally right. We should change the text. Given you already identified the code line would you be up to opening a PR?

**Comment by ingridkindem** [comment]
Great 🤠 Yup, but dosen't look like I have permission to create a branch? Could you help me with that @Lms24 ?

**Comment by lforst** [comment]
@ingridkindem Hi, I recommend taking a look at https://docs.github.com/en/get-started/quickstart/contributing-to-projects if you would like to contribute to open source projects :) Give it a try! It is very satisfying.

**Comment by ingridkindem** [comment]
Will fix
