### ISSUE TITLE
Wizard project selection "glitches" when moving the arrow up

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-wizard#484]
### Environment

-Latest version of wizard.
- Windows 11
- VS Code - Powershell terminal.

### Steps to Reproduce

on the option of selecting the project, scroll down.
then scroll up and it'll start to mark multiple projects as selected.

I also noticed that at first it didn't happen when I was using on my main display (2k resolution), but it started  to break once I tried it on a 1080p display, and continued broken even after moving to the 2k monitor

Not broken video:
https://github.com/getsentry/sentry-wizard/assets/8229322/a5d17894-ca6d-4c43-a5b5-b37fac4f4598
Broken video:
https://github.com/getsentry/sentry-wizard/assets/8229322/2ed12990-616d-4803-8e9f-3faba42c8cd0

### Expected Result

to only a single project to be marked as the selected one.

### Actual Result

it seems to only happen when you  move the arrow up.
![image](https://github.com/getsentry/sentry-wizard/assets/8229322/e3b8e9da-8a00-49a2-be29-085be8edd2e0)

BONUS POINTS:
Allow to search the project by typing the name of it, it's quite hard to find the correct project since the project names aren't sortedby their names but by the org's name

**Comment by Lms24** [comment]
@lucas-zimerman I think this happens when the height of the terminal window is smaller than the "page height" of the project list. Does this bug disappear if you increase the terminal window height?

Currently, we configured clack to show 12 projects per page. Maybe we should reduce this to something between 5-8?

**Comment by lucas-zimerman** [comment]
It seems to glitch when the terminal window size is around 1219x399 pixels
<img width="629" alt="image" src="https://github.com/getsentry/sentry-wizard/assets/8229322/63eedefa-cfc4-4871-a1fa-f5f68b6bcf7c">
Resizing to fullscreen seems to fix it (note the top is just garbage of unchanged text on the buffer so its ok)
<img width="237" alt="image" src="https://github.com/getsentry/sentry-wizard/assets/8229322/9cdebe42-e032-4fb8-b10a-292d6fd05615">

My suspicious is that the  Wizard requires 16 vertical character lines available, anything lower than that seems to glitch the scroll and the list
<img width="258" alt="image" src="https://github.com/getsentry/sentry-wizard/assets/8229322/0f25330f-450d-4103-96f3-2f04fb6ba383">
<img width="358" alt="image" src="https://github.com/getsentry/sentry-wizard/assets/8229322/11f1b59b-4957-42c9-8ee4-ca1efbf82b81">


By default on my VSCode I have 13 visible vertical character lines so it'll glitch on the small monitor, where on the larger monitor i have 15 vertical lines.

**Comment by Lms24** [comment]
I wonder if we can detect the number of lines and adjust the sliding window/page size for the list accordingly

**Comment by Lms24** [comment]
backlogging for now but don't have time to look into it in greater detail

**Comment by lucas-zimerman** [comment]
this is an issue with the library itself, this could be fixed once https://github.com/natemoo-re/clack/pull/174 is merged.

**Comment by Lms24** [comment]
Closing as project selection has been moved to the in-browser login flow
