### ISSUE TITLE
Add configs for capacitor (Ionic Angular project)

### ISSUE THREAD

**Issue by SerjMalko** [getsentry/sentry-wizard#485]

**Comment by Lms24** [comment]
Hi @SerjMalko thanks for writing in! We might consider this in the future but at least from the JS SDK team's end, we don't have the necessary ressources to work on a new wizard at the moment. (Gonna cc @kahest for Mobile perspective)

If you want to take a look at this yourself, PRs are always welcome and appreciated! Our [SDK setup wizard guidelines](https://develop.sentry.dev/sdk/setup-wizards/) might be helpful if you decide to work on this.

**Comment by Lms24** [comment]
Fwiw, given that Angular isn't the only FE framework that can be used with capacitor/ionic, the complexity of creating such a wizard is quite high. Maybe it makes sense to tackle the individual frameworks first.
