### ISSUE TITLE
Update Wizard for Vite in Remix 2.2

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#487]
### Description:

Starting with Remix 2.2 has unstable support for Vite, meaning we may need to consider that Remix users may be using Vite already with this version, and at some point in the future it might be the default.

### Requirements:

Remix and source maps wizard(s) should consider this nuance and be able to react accordingly, whether that be with an initial question to the user, or detection based on some combination of dependencies, versions, and config files.

https://remix.run/blog/remix-heart-vite

### Deliverables:

- [x] Remix Wizard Update (https://github.com/getsentry/sentry-wizard/pull/495)
- [x] Source maps wizard update (https://github.com/getsentry/sentry-wizard/pull/495)
- [ ] Remix Docs update

**Comment by Lms24** [comment]
Reopening because this got auto closed via #495. I belive, docs are still missing, correct @onurtemizkan ?

**Comment by Lms24** [comment]
Oh, nevermind, the docs are tracked in https://github.com/getsentry/sentry-javascript/issues/9421. Closing this one then. (but please still do it anyway)
