### ISSUE TITLE
Keyboard stucked on "Which framework, bundler or build tool are you using?"

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-wizard#492]
### Environment

What version are you running? Etc.

latest | 3.9.0 (also tested with 3.16.2)

### Steps to Reproduce

I have selected a project, when the screen to select the framework was shown, I could only select "anglular", pressing the arrow up and arrow down key didn't move the cursor to other options.

### Expected Result

To select another option than Angular

### Actual Result

<img width="413" alt="image" src="https://github.com/getsentry/sentry-wizard/assets/8229322/8ec563c1-7984-41f1-b58f-7e8c1300202d">
I can't say alot, but I know previously this option  was allowing me to select other frameworks.

EDIT:
<img width="462" alt="image" src="https://github.com/getsentry/sentry-wizard/assets/8229322/9b22d404-e02b-45fc-98bb-0500d83d4af3">
I believe it may be wrongly reading the keyboard, maybe it's reaching an entire line and allowing it to type anything during this menu instead of reading a single char and processing it?

**Comment by lucas-zimerman** [comment]
https://github.com/getsentry/sentry-wizard/assets/8229322/12b59ad6-18fe-414b-bc1c-785b0ef3646a

Added a video to show what is going on, it seems like it enters a code that reads a line, and once you press enter, it start a loop for reading the arrow keys and selecting which framework I should use.

**Comment by Lms24** [comment]
I tried reproducing this but I can't on MacOS. Wondering if this is a Windows-specific problem. Would you mind raising an issue in https://github.com/natemoo-re/clack? That's the library we use for the CLI prompts.

**Comment by the133448** [comment]
+1 Also having this problem. @Lms24 I don't think it would be a problem with the upstream lib for reading prompts as the previous multi select prompt for Sentry project works fine on windows.

**Comment by igorcrevar** [comment]
I have exactly the same problem: Windows 11, React app

**Comment by lucas-zimerman** [comment]
https://github.com/natemoo-re/clack/issues/176
The spinner is breaking it once we stop it

**Comment by lucas-zimerman** [comment]
I suggested some fixes on the library but if they aren't merged we probably can just clone the spinner and apply the fixes locally.

**Comment by Lms24** [comment]
@lucas-zimerman thanks a lot! Also saw the PR that's fixing this in the clack repo. 

> we probably can just clone the spinner and apply the fixes locally

Yup, we did this before a while ago. Suggestion: let's give them a bit of time over the holidays and then apply the fix locally if still necessary.

**Comment by Lms24** [comment]
This came up again in https://github.com/getsentry/sentry-wizard/issues/523. Let's give them two more weeks otherwise we have to vendor in the fix. (this might generally be a reason to look for alternatives to clack)

**Comment by marty0678** [comment]
Having this issue too, is there a workaround in the mean time aside from setting up the environment in WSL or something?

**Comment by lucas-zimerman** [comment]
> Having this issue too, is there a workaround in the mean time aside from setting up the environment in WSL or something?

I usually just type enter when it happens so it unlocks the keyboard

**Comment by marty0678** [comment]
Interesting, that didn't work for me (nothing on the keyboard worked). I just manually set it up in the end.

**Comment by fmgrafikdesign** [comment]
Same issue on Win10 for a vue 3 app, initiated via `npx @sentry/wizard@latest -i sourcemaps`. It preselects "I use another tool [...]" and doesn't let me select anything else. I tried it with both `cmd.exe` and `powershell.exe`.

**Comment by Lms24** [comment]
I talked to the clack maintainer and he's going to take a look at the open PR fixing this issue soon. Let's give them a couple of more days.

**Comment by gramliu** [comment]
+1 I am also experiencing this issue on Windows. I do see that the fix on clack got merged recently though: https://github.com/natemoo-re/clack/pull/182

**Comment by Lms24** [comment]
Hey all, version 3.20.5 of the wizard should fix this problem. Please let us know if the problem still persists or if it is fixed, thanks 🙏 

Also props to @gramliu for contributing the PR!
