### ISSUE TITLE
Deprecated  `configureScope` is used in a few templates

### ISSUE THREAD

**Issue by roottool** [getsentry/sentry-wizard#519]
## Overview

Deprecated `configureScope` is included in two templates. Currently, we are recommended to use `getCurrentScope`.

> Deprecate `configureScope` in favor of using `getCurrentScope()`
> https://github.com/getsentry/sentry-javascript/blob/812d10ad815773ca3c584b6187388c2f208a69ce/MIGRATION.md#deprecate-configurescope-in-favor-of-using-getcurrentscope

## Expected behavior

`getCurrentScope` is used in place of `configureScope`.

## Actual behavior

`configureScope` is used.

- https://github.com/getsentry/sentry-wizard/blob/a16b3cd4b0022644be4c33a77fb01d913c8586e4/src/nextjs/templates.ts#L223
- https://github.com/getsentry/sentry-wizard/blob/a16b3cd4b0022644be4c33a77fb01d913c8586e4/src/sveltekit/templates.ts#L70

**Comment by Lms24** [comment]
Hey @roottool thanks for raising this! We need to adjust the templates here - you're absolutely right. I added it to our v8 TODO list and will expedite fixing this so that we don't ship soon-to-be outdated code to our users.
