### ISSUE TITLE
Sentry Wizard should not be opinionated 

### ISSUE THREAD

**Issue by kenn** [getsentry/sentry-wizard#521]
### Environment

Sentry Wizard for Remix

### Steps to Reproduce

1. `npx @sentry/wizard@latest -i remix`

### Expected Result

It should make minimal changes to the original source, only add wrapper, unmodified anywhere else.

<img width="1184" alt="Screenshot 2023-12-23 at 11 19 20" src="https://github.com/getsentry/sentry-wizard/assets/10350/0b8dd72b-443d-4da6-b1c3-ef7780f97e0f">

### Actual Result

It also changes how new lines should be removed at each file, or add semicolon. Respect our preference. :)

<img width="1182" alt="Screenshot 2023-12-23 at 11 19 08" src="https://github.com/getsentry/sentry-wizard/assets/10350/41f6fae5-2c64-41f4-9ad2-dcec4810e6bb">

**Comment by Lms24** [comment]
Hi @kenn, thanks for writing in! 

I generally agree with you that our wizard shouldn't format things differently to your preferred style. 

However, we use `recast` which already has quite a bit of logic built in to detect the format of the file it parses and apply the same format when writing the modfied AST back to the file. 

It might be worth checking our recast settings to be sure we do our best here but other than that I believe it's unlikely that we'll ever be able to always apply the exact formatting style.

Worth noting that also the Astro CLI (which for me is the gold standard for code mod wizards) a lot of the time gets formatting wrong. It's a tricky problem to solve.

If you have concrete ideas to improve things, I'm always happy to review PRs. Leaving this open for the time being but as I said it's unlikely that we can do a lot here.

**Comment by kenn** [comment]
Got it. [Prettier](https://prettier.io/) fixes it on save, so it's not a big deal. I just wanted to report in case it's missed, but feel free to close this issue!

**Comment by Lms24** [comment]
We briefly discussed trying to detect if a project uses prettier and, if yes, running prettier from within the wizard. I think we didn't investigate this in greater detail due to time constraints but we could also revisit this idea.

**Comment by kenn** [comment]
That sounds like a good idea! Thanks @Lms24
