### ISSUE TITLE
Can't install sentry on nextjs 13.4.19

### ISSUE THREAD

**Issue by 1mehdifaraji** [getsentry/sentry-wizard#530]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. npx @sentry/wizard@latest -i nextjs

### Expected Result

Installation finished

### Actual Result

│  error An unexpected error occurred: "EINVAL: invalid argument, mkdir '/Users/mehdi/Desktop/pwa/node_modules/@next/eslint-plugin-next/node_modules'".

![Screenshot 1402-11-08 at 10 12 09](https://github.com/getsentry/sentry/assets/63982703/ffc82a90-b915-4f0e-aa11-a93758d74bae)

### Product Area

Issues

**Comment by lforst** [comment]
Hi, we need a little bit more information.

- What step did the wizard fail on?
- What package manager are you using?

Also, can you try deleting your node_modules, and cleaning up your users' global node modules? I do not think this is an issue with the wizard but an issue with your package manager, or one of the installed dependencies.

**Comment by 1mehdifaraji** [comment]
I did solve the issue by deleting `node_modules` and `yarn install`. Then the error disappeared. Seems like it was the package manager issue.
