### ISSUE TITLE
Error during setup with wizard on a brand new react-native project

### ISSUE THREAD

**Issue by nromptea42** [getsentry/sentry-wizard#531]
### Environment

macOS `14.2.1 (23C71)`
node `v20.6.1`
npx `v9.8.1`
yarn `v1.22.19`
react-native `0.73.3`

### Steps to Reproduce

```
$ npx react-native init Test123
$ npx @sentry/wizard -s -i reactNative
```

### Expected Result

The documentation said that the wizard would patch the natives files but it stopped during the installation of the package.

### Actual Result

![Screenshot 2024-01-30 at 17 41 37](https://github.com/getsentry/sentry-wizard/assets/9318179/463005cc-8794-4c87-a497-29f341e8e99f)

During the step `Installed @sentry/react-native with Yarn.` I got this :
```
TypeError: Cannot read properties of undefined (reading 'dsn')
    at /Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/wizard/dist/src/react-native/react-native-wizard.js:179:81
    at /Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/wizard/dist/src/telemetry.js:129:90
    at handleCallbackErrors.handleCallbackErrors.status.status (/Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/core/cjs/tracing/trace.js:85:13)
    at Object.handleCallbackErrors (/Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/core/cjs/utils/handleCallbackErrors.js:26:26)
    at /Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/core/cjs/tracing/trace.js:84:33
    at Hub.withScope (/Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/core/cjs/hub.js:145:28)
    at Object.withScope (/Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/core/cjs/exports.js:170:20)
    at startSpan (/Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/core/cjs/tracing/trace.js:74:20)
    at traceStep (/Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/wizard/dist/src/telemetry.js:129:33)
    at /Users/nathan/.npm/_npx/ddb126e78325956c/node_modules/@sentry/wizard/dist/src/react-native/react-native-wizard.js:178:68
```

Maybe I did something wrong or I'm using an unsupported version. Feel free to let me know if you need anything else.
Thank you

**Comment by Lms24** [comment]
Hi @nromptea42 thanks for writing in! 

Gonna tag @krystofwoldrich - could you take a look at this please? Thanks!

**Comment by ElSeniorMikael** [comment]
I also experience a similar error, whenever i try to setup sentry on my app it give me this error.

![Screenshot 2024-02-01 at 1 59 30 PM](https://github.com/getsentry/sentry-wizard/assets/73765089/65ba185b-3557-4ffc-ba2b-b567df9e6a89)

At first i thought the cause of the error is my app.tsx already having the declaration of sentry so i tried to remove it and let sentry do it.

![Screenshot 2024-02-01 at 2 01 33 PM](https://github.com/getsentry/sentry-wizard/assets/73765089/b62fa1c4-8126-4cd6-b18e-0ac02a9d8df9)

But i still receive this error

**Comment by Lms24** [comment]
Hey @ElSeniorMikael thanks for reporting! I believe the problem you're experiencing happens at a later stage but we'll take a look.

**Comment by krystofwoldrich** [comment]
Hi everyone,
the original error `/@sentry/wizard/dist/src/react-native/react-native-wizard.js:179:81` is caused by the Sentry API not returning a DSN for the selected project.

**Comment by ElSeniorMikael** [comment]
> Hey @ElSeniorMikael thanks for reporting! I believe the problem you're experiencing happens at a later stage but we'll take a look.

Would you rather i make a new issue or we can do the follow up over here ?

**Comment by krystofwoldrich** [comment]
@ElSeniorMikael A new issue would be better.

**Comment by nromptea42** [comment]
> Hi everyone, the original error `/@sentry/wizard/dist/src/react-native/react-native-wizard.js:179:81` is caused by the Sentry API not returning the selected project.

Should I create and use a new project in my organisation ? Or is it a problem with my organisation ?

**Comment by Lms24** [comment]
@nromptea42 if you try creating a new project, does anything change for you?

**Comment by nromptea42** [comment]
> @nromptea42 if you try creating a new project and selecting it in the wizard does anything change for you?

Hello, it worked after creating a new project and using it.
I'm closing this, thanks a lot !
