### ISSUE TITLE
Add `spotlight: true` comment to relevant `Sentry.init` snippets  

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-wizard#535]
Our wizard should inject a commented `spotlight: true` flag to enable sending events from the SDK to the spotlight sidecar:

```js
Sentry.init({
  dsn: '...',
  //...
  // uncomment this to enable Spotlight (https://spotlightjs.com):
  // spotlight: true
})
```

For now, the following platforms come to mind:
* NextJS server-side
* SvelteKit server-side
* Remix server-side

Client-side is taken care of by the spotlight overlay (which injects the integration into the Sentry SDK). 

Also
* React Native (?)
* Electron (?)
* Not sure about the state in iOS/Android

**Comment by Shubhdeep12** [comment]
Hey @Lms24 should we do this? For the platforms where we spotlight is supported.

**Comment by Lms24** [comment]
Hey, @Shubhdeep12 yes, let's give this a try! If you take a look at this, let's please first tackle the JS frameworks with one PR per framework (to keep things a bit easier to review and revert if necessary). Let me know if you have questions around the wizard.

**Comment by Shubhdeep12** [comment]
Sure, i'll do it in the same way.

**Comment by Shubhdeep12** [comment]
Hi @Lms24 Added the PRs

Please check.
Thanks

**Comment by Lms24** [comment]
Hey @Shubhdeep12 sorry for the late reaction to this PR! I missed that you reworked it and didn't look at it earlier. 

Here's the thing: In the meantime, we implemented feature selection in the wizard, with the plan to eventually also make spotlight a selectable feature. Then we don't have to worry about the comment shenanigans and can actually enable spotlight on user selection. I would argue though that we should tackle this separately in a new issue when the time is ready for this. If we were to rebase and re-integrate this PR, we'd have to change a signficant part of the Remix SDK init call creation logic. 

Therefore, for the moment, I'm going to close this PR.
