### ISSUE TITLE
Callout Next.js Tunnel option and prompt if it should be enabled by default or not

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-wizard#554]
We should add this as a prompt to the setup wizard to ensure users are not surprised.

**Comment by lforst** [comment]
I wouldn't do this. Adds complexity in setup with a pretty obscure concept that beginners don't and it very likely wouldn't have prevented the situation that spawned this issue.

**Comment by HazAT** [comment]
We should make it opt-in by default, no surprises.
