### ISSUE TITLE
Running "npx @sentry/wizard@latest -i remix" does not populate Sentry.init

### ISSUE THREAD

**Issue by bcoe** [getsentry/sentry-wizard#559]
### Environment

```
$ node --version
v20.11.1
```

```
$ npx @sentry/wizard@latest --version
Need to install the following packages:
@sentry/wizard@3.22.0
```

### Steps to Reproduce

1. Ran `npx @sentry/wizard@latest -i remix` on a remix project.
2. Walked through wizard.
3. Observe that `Sentry.init()` isn't called anywhere in the code that's populated.

### Expected Result

React project is configured such that it will start sending errors up to Sentry.

### Actual Result

Deployed the application and was confused because it was not configured to send errors to Sentry.

**Comment by Lms24** [comment]
Hey @bcoe thanks for writing in and apologies for the late reply! 

This sounds a bit off and definitely shouldn't happen. The wizard should add `Sentry.init` calls to `entry.client.tsx` as well as `entry.server.tsx` as outlined in our [manual setup instructions](https://docs.sentry.io/platforms/javascript/guides/remix/manual-setup/#server-side-configuration). I know it's been a while but do you by any chance recall if you got any warnings during the wizard run? Is your remix project set up somehow (vastly) different from a default remix project?
