### ISSUE TITLE
Dynamically import `package.json` instead of `JSON.parse`ing it

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-wizard#561]
Alternative issue title: There's no such thing as stability in JS-land

Looks like Bun is going to permit comments in `package.json` (https://github.com/oven-sh/bun/pull/10287). This will break our wizard which currently reads users' `package.json` files and parses them with `JSON.parse`. `JSON.parse` throws when it encounters comments. We catch this in the wizard but this obviously degrades the setup flow (iirc we even early return in some cases, e.g. sourcemaps wizard). 

If they go through with this change, we need to move to an alternative parsing method. I guess we could try to dynamically `import` the file instead but iirc we tried this before and ran into some issues. Opening this issue to track the problem.

Prio-wise, I'd argue this is low because:

1. It's still discouraged to add comments, bun just won't error on it. Still, this opens up a new class of problems
2. Users have to use bun because npm et al. would already error
3. Users have to actually put comments into their package.json

Until we get to this, we'll need to tell folks to _not_ add comments into their `package.json`.

**Comment by lucas-zimerman** [comment]
It's kinda wild that solution was accepted, I'd rather make some plugin for vscode where it parses some `package.json.comment` file and it just applies the comments as a visual effect on package.json, allowing folks to see the comments and also not breaking the JSON standard.

**Comment by Lms24** [comment]
For now I'll close this issue due to priorization. We can re-open when this becomes problematic IRL. If anyone experiences problems please feel free to tag me so that we can reopen this.
