### ISSUE TITLE
What is the expected output of sentry-wizard for android?

### ISSUE THREAD

**Issue by nienienienie** [getsentry/sentry-wizard#565]
I used sentry-wizard for android and the only things that happend:

1.  on my sentry server instance a token was created
2. a file `sentry.properties` was created locally
3. that token (1) was added to the file (2)
4. added an example error to my app's Main Activity

But afaik there are more steps needed to have sentry capture errors - at least DSN is needed to be configured (besides 1-4 from above) as per https://docs.sentry.io/platforms/android/manual-setup/.

**Comment by nienienienie** [comment]
what I see in https://github.com/getsentry/sentry-wizard/issues/512#issuecomment-1880878917 this is expected but I can't understand why. It's rather unexpected for me and the wizard does not seem useful.

**Comment by nienienienie** [comment]
To the contrary https://docs.sentry.io/platforms/android/#install it says:
> It'll then automatically do the following steps for you:
update your app's build.gradle file with the Sentry Gradle plugin and configure it
update your AndroidManifest.xml with the default Sentry configuration
create sentry.properties with an auth token to upload proguard mappings (this file is automatically added to .gitignore)
add an example error to your app's Main Activity to verify your Sentry setup

**Comment by Lms24** [comment]
Hey @nienienienie thanks for writing in! Gonna ask @romtsn to please take a look, thanks!

**Comment by romtsn** [comment]
@nienienienie it should still do the following two:
> update your app's build.gradle file with the Sentry Gradle plugin and configure it
update your AndroidManifest.xml with the default Sentry configuration

can you check those files? If they are not updated, could you post output of the `sentry-wizard -i android` command?

**Comment by nienienienie** [comment]
ok, false alarm - I was running wizard on already configured project (years ago) so wizard was not doing all the stuff that I expected (because some were already there)
