### ISSUE TITLE
Wizard doesn't include config file for build phases script

### ISSUE THREAD

**Issue by elramen** [getsentry/sentry-wizard#569]
### Steps to Reproduce
1. Create a new iOS project in xcode
2. Create new iOS project in sentry.
3. Run the wizard inside the xcode project dir (brew install getsentry/tools/sentry-wizard && sentry-wizard -i ios)
4. Build the xcode project.

### Expected Result
Debug files get uploaded

### Actual Result
Debug files don't get uploaded, instead an error happens:
"warning: sentry-cli - error: Failed to load .sentryclirc file from project path (/Users/elias/Documents/adad/.sentryclirc)
  caused by: Operation not permitted (os error 1)
sentry-cli - error: Failed to load .sentryclirc file from project path (/Users/elias/Documents/adad/.sentryclirc)"

### Ideas
By manually adding "$(SRCROOT)/.sentryclirc" to the "Input Files" of the build phases script "Upload Debug Symbols to Sentry", everything works as expected. Hence, it would be great if the wizard would automatically do this.

**Comment by Lms24** [comment]
Hey @elramen thanks for writing in! I'm gonna tag @brustolin - would you mind taking a look at this? Thanks!

**Comment by brustolin** [comment]
Hello @elramen, did you changed the value of `ENABLE_USER_SCRIPT_SANDBOXING` in your project settings?

**Comment by brustolin** [comment]
> Hey @brustolin, I did not make any manual changes. The value is "Yes".

This is the problem. The value should be "No". 
Xcode 15 changed the default value, we need to update the wizard.
