### ISSUE TITLE
react-native: javascript not patched when using typescript

### ISSUE THREAD

**Issue by wodCZ** [getsentry/sentry-wizard#58]
The current template for new react native projects using typescript has `App.tsx` file instead of `App.js`.
When running the wizard, I've noticed this output:
```
✅ Patched build.gradle file.
✅ Patched App.js file.
✅ Added sentry.properties file to android
Successfully set up android for react-native
✅ Patched build script in Xcode project.
✅ Patched App.js file.
✅ Added sentry.properties file to ios
Successfully set up ios for react-native
```
And I confirmed, the  App.js file was not patched (it doesn't exist) - the step passed without actually patching anything.

Link to current typescript template: https://github.com/react-native-community/react-native-template-typescript/tree/master/template
Link to current steps to initialize react native project with typescript: https://facebook.github.io/react-native/docs/typescript

I think adding another block here: https://github.com/getsentry/sentry-wizard/blob/master/lib/Steps/Integrations/ReactNative.ts#L51-L63
would fix this step:
```
await patchMatchingFile(
    'App.tsx',
    this.patchJs.bind(this),
    answers,
    platform,
);
```

But probably this section of code could be refactored to more sophisticated context detection.

**Comment by tomdaniel0x01** [comment]
I had the same problem.

**Comment by leonardoballand** [comment]
same problem here

**Comment by wodCZ** [comment]
The issue still exists: sentry-wizard doesn't support official react-native typescript starter.
I haven't tested lately, but I believe it's still "lying" about that the wizard finished successfully (while it did not).

**Comment by krystofwoldrich** [comment]
Yes, wizard 2.1.0 and newer supports the official TS template.
