### ISSUE TITLE
Wizard prints multiple initial logs

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-wizard#596]
Some of them are confusing and duplicate.

![Screenshot 2024-06-19 at 10 58 11](https://github.com/getsentry/sentry-wizard/assets/8118419/4a843ee6-7eff-498a-a4f4-a1d4091af969)

**Comment by Lms24** [comment]
IMO we should revisit short circuiting the step-based code entirely for all flows based on clack. I think this requires us to rewrite the initial integration/flow selection (for folks starting the wizard without the `-i` flag)  in clack but that's fine. This should get rid of all console logs prior to clack starting. WDYT?

**Comment by lforst** [comment]
BIG +1
