### ISSUE TITLE
Option to skip platforms in sentry-symbols.js

### ISSUE THREAD

**Issue by JohnHardy** [getsentry/sentry-wizard#67]
Hello,

We were recently debugging a native electron crash and decided to upload the symbols.  

We do not have a great internet connection, so were put off by the 1.3GB of native darwin symbols.  The Windows ones were only a few meg.

Please can you add the option to skip symbols for certain platforms?  

We ended up commenting out chunks of the script to do the bits we needed.

**Comment by Lms24** [comment]
Closing due to cleaning up this repository. Please let us know if this is still an issue, then I'll reopen this issue. In case it is, please also let us know what you expect the Sentry Wizard to do in this case. Thanks!
