### ISSUE TITLE
can't download sentry-wizard

### ISSUE THREAD

**Issue by hhmy27** [getsentry/sentry-wizard#683]
curl: (35) Recv failure: Operation timed out #

Error: sentry-wizard: Failed to download resource "sentry-wizard"

**Comment by Lms24** [comment]
Hey @hhmy27 thanks for opening this issue! Can you describe what specific command you executed that produced this error message?

**Comment by hhmy27** [comment]
Hi @Lms24 

I'm using the official command for downloading `brew install getsentry/tools/sentry-wizard && sentry-wizard -i ios`, And everything is going well, but an error occurs when downloading sentry-wizard.

I have modified the download source configuration for brew. Below is my configuration:
```
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
```

I'm not sure if these two mirror sources have synchronized sentry-wizard yet.

Finally, I tried to manually install and integrate Sentry.

**Comment by Lms24** [comment]
Hmm I see @romtsn who added the wizard to brew. Any ideas what could be going on here?

**Comment by romtsn** [comment]
@hhmy27 we publish the wizard to a custom tap (`getsentry/tools`), not sure if your mirror supports synchronizing custom taps. From what I grasped, it only synchronizes the following repos:

> The mirror site provides the following under the https://github.com/Homebrew organization repo: brew, homebrew-core, homebrew-cask, homebrew-command-not-found, install.

That said, I don't know if we can do anything on our side in this case.

**Comment by hhmy27** [comment]
> [@hhmy27](https://github.com/hhmy27) we publish the wizard to a custom tap (`getsentry/tools`), not sure if your mirror supports synchronizing custom taps. From what I grasped, it only synchronizes the following repos:
> 
> > The mirror site provides the following under the https://github.com/Homebrew organization repo: brew, homebrew-core, homebrew-cask, homebrew-command-not-found, install.
> 
> That said, I don't know if we can do anything on our side in this case.

Thanks, it was caused by me changing the mirror source, let me switch back to the original settings for downloads
