### ISSUE TITLE
Unable to login with Source Maps Upload Configuration Wizard

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry-wizard#696]
### Environment

What version are you running? Etc.
3.34.2
### Steps to Reproduce

1. Run bunx @sentry/wizard@latest -i sourcemaps or npx @sentry/wizard@latest -i sourcemaps --saas
2. go through steps "Do you already have a Sentry account?"
3. the url does not successfully authenticate via the browser window that is opened. Also tried:
* pasting the url
* pasting the url in an incognito browser
[issue in sentry](https://sentry.sentry.io/issues/6017915270/events/6b3ee3593aae4dab8763844dd22c25af/)
![Image](https://github.com/user-attachments/assets/ec8ca8fa-97b2-44e7-9130-928d2f0aa150)
![Image](https://github.com/user-attachments/assets/25212001-583f-4fe7-91b3-57b1b51d94ee)

### Expected Result

Successful login

### Actual Result

Unable to login

**Comment by lforst** [comment]
Thanks for the report! This should be fixed with https://github.com/getsentry/getsentry/pull/15518. The Sentry error also no longer shows this happening.
