### ISSUE TITLE
Electron configuration instructions are wrong

### ISSUE THREAD

**Issue by jlongster** [getsentry/sentry-wizard#7]
The electron integration emits this code to be added to the project:

```js
const Sentry = require('@sentry/core');
const SentryElectron = require('@sentry/electron');

Sentry.create(<url>)
  .use(SentryElectron)
  .install();
```

But this is is wrong (and make me spend a few hours figuring it out). The right code with the current versions of the libraries is:

```js
const { SentryClient } = require('@sentry/electron');
SentryClient.create({
  dsn: <url>
});
```

This is extremely confusing so I'd recommend updating the text.

**Comment by HazAT** [comment]
Thanks for pointing this out, `0.9.3` is out now 👍
