### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by robjpope** [getsentry/sentry-wizard#75]
Hi. Having an issue installing react native to iOS.

Version: 1.1.4

yarn sentry-wizard -i reactNative -p ios

lease select your project in Sentry: xxxxxxxxxx / xxxxxxxxxx
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1380:5)
    at /Users/xxxx/Desktop/apps/xxxxxxxxxxx/node_modules/@sentry/wizard/dist/lib/Helper/File.js:23:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Thanks

**Comment by allandallopez** [comment]
@robjpope is this solved, then how ? i got the same error with you.

**Comment by hanselsen** [comment]
I too have this issue.

**Comment by jameskennethrobinson** [comment]
Also having this issue

**Comment by robjpope** [comment]
> @robjpope is this solved, then how ? i got the same error with you.

Hi. I think from memory I just updated the version NPM version. What version are you using?
