### ISSUE TITLE
More clarity as to the purpose of this wizard

### ISSUE THREAD

**Issue by leojh** [getsentry/sentry-wizard#81]
This wizard seems to be geared only towards mobile and hybrid web/native applications but this is not reflected in any docs that I could find.

This should be more clear or better yet, add support for regular web applications.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
