### ISSUE TITLE
No platform selected

### ISSUE THREAD

**Issue by hanselsen** [getsentry/sentry-wizard#93]
This is a copy of [this issue](https://github.com/getsentry/sentry-react-native/issues/1386). I'm placing it here because it belongs in this repo.

### Environment
How do you use Sentry?
Sentry SaaS

### Which SDK and version?
@sentry/react-native: 2.2.2
react-native: 0.63.3

**Steps to Reproduce**
Follow the installation guide and running
npx @sentry/wizard -i reactNative -p android
Getting this:
`✅ Patched build.gradle file.
Error: No platform selected
at ReactNative.MobileProject.getPlatforms (/Applications/MAMP/htdocs/shkolo/shkolo-mobileapp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/MobileProject.js:65:19)
at ReactNative._patchJs (/Applications/MAMP/htdocs/shkolo/shkolo-mobileapp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:224:14)
at /Applications/MAMP/htdocs/shkolo/shkolo-mobileapp/node_modules/@sentry/wizard/dist/lib/Helper/File.js:28:45
at processTicksAndRejections (node:internal/process/task_queues:94:5)
🎉 Successfully set up Sentry for your project 🎉`3. But android/sentry.properties is not generated and after that when I try to build the android app I get:`

> Task :app:bundleReleaseJsAndAssets_SentryUpload_89 FAILED
> error: An organization slug is required (provide with --org)
> `

**Expected Result**
The Sentry setup should be successful and the app should be build successfully

**Actual Result**
I get both errors described in the steps.

**Comment by hanselsen** [comment]
I decided not to be lazy and used [the manual configuration](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/). It is now working for me. Hopefully other people will get to enjoy the wizard.

**Comment by bruscantini** [comment]
I too am facing this error. And when I try to link manually, I get this from RNSentry.h:
`'RCTBridge.h' file not found`
